{% set name = "robocorp" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robocorp-{{ version }}.tar.gz
  sha256: 9ffbff0c55f2f26abbb75c39d0976b9fefaafd8a78776f970e6c42c05ca4152c

build:
  noarch: python
  script:
    - echo f | xcopy /f /y /S %RECIPE_DIR%\README.md %SRC_DIR%\README.md  # [win]
    - cp -R {{ RECIPE_DIR }}/README.md {{ SRC_DIR }}/README.md  # [unix]
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - robocorp-tasks 2.1.3
    - robocorp-log 2.6.0
    - robocorp-workitems 1.3.0
    - robocorp-vault 1.2.0
    - robocorp-storage 0.3.2

test:
  imports:
    - robocorp
    - robocorp.tasks
    - robocorp.log
    - robocorp.workitems
    - robocorp.vault
    - robocorp.storage
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/robocorp/robo/
  summary: Robocorp core libraries for Python automation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
